[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "poethepoet>=0.48.0",
  "pyright>=1.1.414",
  "ty"
]

[project]
name = "crm-jobs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "django>=6.1.1",
  "pytest>=9.1.1",
  "pytest-cov>=4.1.0",
  "pytest-django>=4.14.0",
  "ruff>=0.16.8"
]

[tool.hatch.build.targets.wheel]
packages = ["src/config", "src/jobs"]

[tool.commitizen] # https://commitizen-tools.github.io/commitizen/config/
bump_message = "bump(release): v$current_version → v$new_version"
tag_format = "v$version"
update_changelog_on_bump = true
version_provider = "pep621"

[tool.coverage.report]
exclude_also = [
  "if TYPE_CHECKING:"
]

[tool.poe]
include = "Taskfile.toml"

[tool.pyright]
include = ["src/config", "src/jobs"]
exclude = [".venv", ".git", "clasp", "src"]

[tool.pytest.ini_options] # https://docs.pytest.org/en/latest/reference/reference.html#ini-options-ref
DJANGO_SETTINGS_MODULE = "src.config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
pythonpath = [
  ".",
  "src"
]
testpaths = [
  "src"
]
addopts = [
  "--cov=src/jobs/",
  "--cov-report=term",
  "--cov-report=html:coverage/html",
  "--cov-report=xml:coverage/coverage.xml",
  "--junitxml=coverage/junit/test-results.xml",
  "--color=yes",
  "--strict-config",
  "--strict-markers"
]

[tool.pytest_env]
ENVIRONMENT = "test"

[tool.ty.terminal]
output-format = "full"
